src/DevAdventCalendarCompetition/DevAdventCalendarCompetition.Repositiory/Migrations/20181021191423_FixedMappings.Designer.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition.Repositiory/Migrations/20181021191423_FixedMappings.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition.Repository/Models/ApplicationUser.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition.Repository/Models/ModelBase.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition.Repository/Models/Test.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition.Repository/Models/TestAnswer.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition.Services/BaseTestService.cs
As in title
Repository project
#10 
Those were commented changes from old competition app. As we have simple relations model, we don't need extra class for mappings, data annotations in model classes are enough.
App is compiling and starting, migration creates working db
=> Replaced mappings with data annotations and added migration

src/DevAdventCalendarCompetition/DevAdventCalendarCompetition.Services/AdminService.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition.Services/BaseTestService.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition.Services/DevAdventCalendarCompetition.Services.csproj, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition.Services/HomeService.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition.Services/Profiles/TestAnswerProfile.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition.Services/Profiles/TestProfile.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition.Services/Startup.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition.Tests/DevAdventCalendarCompetition.Tests.csproj, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition.Tests/MapperTest.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition.sln
Fixed configuration and added tests for mapper configuration
Run app, run tests
#22 
Class _MapperTest_
=> Added automapper profiles

src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/wwwroot/css/site.css
Update style.css to unify font family and colors.
Update site.
Unify font and colors. #67
=> update site.css style to fit font family and colors

src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Account/ForgotPassword.cshtml, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Account/ForgotPasswordConfirmation.cshtml, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Account/Login.cshtml
Reorganize the login page view
Translation eng->pl
Login.cshtml
Login page in eng
=> Translate login page

.gitignore, src/DevAdventCalendarCompetition/docker-compose.prod.yml
Docker compose file for production server deployment.
As in title.
Check if app is working on production - this compose is specific for deployment server, there's nothing much to review here
I't required for CD #4 
Production env was created from this compose file.
=> Added production compose file

src/DevAdventCalendarCompetition/DevAdventCalendarCompetition.Services/AdminService.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition.Services/BaseTestService.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition.Services/HomeService.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition.Tests/AdminServiceTest.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition.Tests/BaseTestServiceTest.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition.Tests/HomeServiceTest.cs
Updated test logic to pass test
Run app, run tests
Class AdminServiceTest, BaseTestService, HomeServiceTest
=> update logic in AdminService, BaseTestService, HomeService

src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Account/ExternalLogin.cshtml
As in commit title.
Try register with external login provider and check if text is in polish.
#101
By registering with external provider on local dev environment
=> Translated external providers register page

src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Controllers/AccountController.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Extensions/StartupExtensions.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Account/Login.cshtml, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Account/Register.cshtml
Added email confirmation mechanism for external login providers. 
This should fix problem with re-redirecting to register page after authenticating with external providers.
Setup app settings on local machine to include provider keys, add localhost temporary callback url in external apps and try to log in with every provider. 
#94 
As described in "Where should the reviewer start?" section, except github provider.
=> Added email confirmation for external login providers

src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Controllers/AccountController.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Controllers/AdminController.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Controllers/ManageController.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Controllers/Test1Controller.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Controllers/Test2Controller.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Controllers/Test3Controller.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Controllers/Test4Controller.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Controllers/Test5Controller.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Controllers/Test6Controller.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Account/AccessDenied.cshtml, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Account/Lockout.cshtml, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Account/SendCode.cshtml, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Account/SignedOut.cshtml, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Account/VerifyCode.cshtml, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Home/Results.cshtml, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Home/Rules.cshtml, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Home/TestAnswered.cshtml, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Home/TestHasEnded.cshtml, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Home/TestHasNotStarted.cshtml, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Shared/Answered.cshtml, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Shared/Lockout.cshtml, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Test1/Index.cshtml, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Test2/Index.cshtml, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Test3/Index.cshtml, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Test4/Index.cshtml, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Test5/Index.cshtml
Translate messages in Controllers, Views, Vms
Run app.
#74
Run app, go to views.
=> Translate messages in DevAdventCalendarCompetition

src/DevAdventCalendarCompetition/DevAdventCalendarCompetition.Services/BaseTestService.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Controllers/AdminController.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Startup.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Admin/AddTest.cshtml, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Home/Index.cshtml
added missing services configuration in startup; default hours of tests
go to admin page and test adding new test  functionality
#109
=> Updated admin site

src/DevAdventCalendarCompetition/DevAdventCalendarCompetition.Services/Extensions/EmailSenderExtensions.cs
Added information about log in with external provider.
Updated account confirmation email text.
Create new account and check e-mail ;)
It seems that some of people will assume that email confirmation link does auto-login
Email was sent from local environment and it looked ok
=> Updated email text with not so obvious information.

src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Controllers/AccountController.cs
An error was in a controller that was not saving ResetPasswordViewModel with user email between views.
Build, run app.
#120 
Run app, tried to reset password.
=> Fixed an error after unsuccessfull password reset

src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Home/Index.cshtml
Fixed issue with test count calculation.
Build, run app, set started/not started/ended tests.
Run app, switched the test status.
=> Fixed issue with test count calculation.

src/DevAdventCalendarCompetition/DevAdventCalendarCompetition.Repository/HomeRepository.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition.Services/Profiles/TestResultProfile.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition.Services/Profiles/TestWrongAnswerProfile.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Controllers/HomeController.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Home/Results.cshtml, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Vms/TotalTestResultEntryVm.cs
Update results view
Prepare DB Results table filling it with proper results. Then build, run app and go to results page.
#44 
Built, run app, displayed the results page.
- [] Bug fix (non-breaking change which fixes an issue)
=> Update results view

src/DevAdventCalendarCompetition/DevAdventCalendarCompetition.Services/Profiles/TestProfile.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition.Tests/BaseTestServiceTest.cs
Fix not passing tests. 
The reviewer should check changes and run tests. 
#144 
Run unit tests. It was a small fix because it resolves a problem with mapping.
=> Added and extended Automapper mappings.

dockerimage.yml
Added initial GitHub Actions file
Just to test new GitHub CI system
It has not ;)
=> Added simple github action to build image

src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Home/Error.cshtml
Error page title is "Błąd"
Go to /Home/Error
#174
=> Updated error page title

src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Shared/_Layout.cshtml
Removed Login and Register buttons in menu
Run app, open menu: there is no Login and Register buttons
#184 
Run app
=> Temporary removed login and register buttons in menu

src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Controllers/AccountController.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Controllers/HomeController.cs
Updated home routes not tu use "Home" in url
Run app, go to "/Contact" or "/Prizes" page
Open all pages from menu
#186 
Run app - see that "/Home/Contact" etc. doesn't work anymore
=> Updated Routes for Home controller

src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Manage/ChangePassword.cshtml, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Manage/Index.cshtml, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Manage/_Layout.cshtml, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Manage/_ManageNav.cshtml, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Shared/_LoginPartial.cshtml, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/wwwroot/theme-2019/style.css
New layout for Manage User Account. Two pages: Profile and Change Password.
=> Authenticated User: Profile, Change Password

src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Admin/AddTest.cshtml, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Admin/Index.cshtml
Small fixes for original Admin Panel template -  such as adding margins, resize page width.
=> Update Admin Panel layout

src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Home/Index.cshtml, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/wwwroot/theme-2019/js/main.js, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/wwwroot/theme-2019/style.css
After 01.12.2019 it will change countdown section:
to this:
Change system datetime to date after 01.12.2019 - the hero section should change
=> Index Page - Display Hero Section after 01.12.2019

src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/wwwroot/theme-2019/js/main.js
Time left to contest beginning was being displayed incorrectly.
=> Fixed hours/minutes description mismatch.

src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Controllers/SubscriptionController.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Subscription/Confirmed.cshtml, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Subscription/Duplicated.cshtml, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Subscription/GDPRInvalid.cshtml, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Subscription/Removed.cshtml, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Subscription/Success.cshtml
Update layout for Subscription pages to match 2019 theme. Resolves #208 #209 
By going to pages:
1. /Subscription/Confirmed
2. /Subscription/Duplicated
3. /Subscription/GDPRInvalid
4. /Subscription/Removed
5. /Subscription/Success
=> Update Newsletter Subscription Layout to match 2019 theme

src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Controllers/AccountController.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Controllers/AdminController.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Admin/AddTest.cshtml, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Admin/_Layout.cshtml, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Vms/TestVm.cs
- added end date in "add test" view
- remove required attributes in fields containing information about the logo, discount or sponsor
- updated layout for admin views (according to the main layout)
Log in, go to Admin page, add new test
=> Updated admin "add test" view

src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Test/Index.cshtml, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/wwwroot/theme-2019/style.css
=> Update layout for Test page

src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Home/Index.cshtml
=> Update Calendar layout to display 7 days per row

src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Shared/_Layout.cshtml
=> Temporarily removed login/register section due to sponsors bugs.

src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Shared/_Layout.cshtml
Problems which caused #234 were resolved.
=> Enabled register/login section

src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Home/Index.cshtml
=> Removed sponsors (leaved template)

src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Controllers/AccountController.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Account/ExternalLogin.cshtml
Fixed missing validation info during registration with already taken email.
Register email with one provider, then try same email with another provider.
#229
On local environment with fb and twitter providers
=> Fixed missing validation info during registration

src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Account/ForgotPassword.cshtml, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Account/Login.cshtml, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Account/Register.cshtml, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Account/ResetPassword.cshtml, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Admin/AddTest.cshtml, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Manage/ChangePassword.cshtml, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Manage/Index.cshtml, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Manage/SetPassword.cshtml
=> quick fix #231 and removed all asp-validation-summary="All"

src/DevAdventCalendarCompetition/DevAdventCalendarCompetition.Services/Models/TestDto.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Controllers/TestController.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Test/Index.cshtml
Added model errors display for user answer.
#249 
1. Run app, log in.
2. Incorrectly answer a question.
3. See the result.
=> Fixed lack of errors in case wrong answered question.

src/DevAdventCalendarCompetition/DevAdventCalendarCompetition.Services/Models/TestDto.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Controllers/BaseTestController.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Controllers/TestController.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Shared/Answered.cshtml, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Shared/TestAnswered.cshtml
Changed view to be redirected - TestAnswered. Added back to main page button.
#250 
1. Run app.
2. Answer correctly a test.
=> Centering message after correct answer

README.md, src/DevAdventCalendarCompetition/.dockerignore, src/DevAdventCalendarCompetition/.editorconfig, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition.Repository/DevAdventCalendarCompetition.Repository.csproj, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition.Services/DevAdventCalendarCompetition.Services.csproj, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition.Services/EmailNotificationService.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition.TestResultService.Tests/DevAdventCalendarCompetition.TestResultService.Tests.csproj, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition.TestResultService/DevAdventCalendarCompetition.TestResultService.csproj, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition.Tests/DevAdventCalendarCompetition.Tests.csproj, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition.sln, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/.editorconfig, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/DevAdventCalendarCompetition.csproj, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/PaginatedCollection.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Program.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Startup.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/appsettings.Docker.json, src/DevAdventCalendarCompetition/Directory.Build.props
- update of all packages
- more changes in Startup.cs
- fixed HttpClient in EmailNotificationService.cs
I can't test it with DB etc, I don't have all the settings from `appsettings.x.json`.
=> #273 Migrate to .NET Core 3.1 - pushing forward migration

.github/workflows/docker-build.yml, src/DevAdventCalendarCompetition/Dockerfile
Docker image definitely is not a place for execution of unit tests, CI should handle it.
=> Moved run of unit tests from dockerfile to ci

.github/workflows/docker-build.yml
@WTobor here you go
cc: @patrikulus
=> fixed codecov ci

README.md
=> modify readme to start app with docker

README.md, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition.Services/Extensions/EmailSenderExtensions.cs
Updated registration email template: added information about enabling notification; updated readme
register a new user and check the registration email
closes #242 
registered new user and checked registration email
=> Added information about notifications option during registration process

src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Controllers/AccountController.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Controllers/AdminController.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Controllers/ManageController.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Controllers/TestController.cs
Go to Account Login, try to write in  for eg. wrong email, 
notification is display
check other paths with error messages
#302
When we log in with the wrong email, we receive notification.
=> Notifications are displayed 

src/DevAdventCalendarCompetition/DevAdventCalendarCompetition.Services/Interfaces/IManageService.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition.Services/ManageService.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Controllers/ManageController.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Models/Manage/IndexViewModel.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Resources/ExceptionsMessages.Designer.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Resources/ExceptionsMessages.resx, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Manage/Index.cshtml
This PR resolves #316 
When logged in, go to **/Manage/Index** to see Profile Edit form
See #316 
Manual tests
=> Remove Phone Number field from Profile Edit form

src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Admin/_Layout.cshtml
After adding the link in facebook or instagram there should appeared information about the site
https://github.com/DevAdventCalendar/DevAdventCalendar/issues/324
It has been tested by creating server and sharing the link 
- [ X] Bug fix (non-breaking change which fixes an issue)
=> Added Open Graph protocol properties

src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Home/Contact.cshtml, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Home/Sponsors.cshtml
Go to https://sonarcloud.io/dashboard?id=DevAdventCalendar_DevAdventCalendar and fix vulnerabilities (https://sonarcloud.io/project/issues?id=DevAdventCalendar_DevAdventCalendar&resolved=false&types=VULNERABILITY)
After merge should be 0 (no security issues)
I did changes with Views files (Views -> Home -> Contacts, Sponsors)
closes #345 
Application is working correctly, all tests passed
=> fixing sonarcloud vulnerabilities

README.md
I've added missing information about tests in README file.
=> Add missing information about tests in README

src/DevAdventCalendarCompetition/DevAdventCalendarCompetition.Services/Resources/ViewsMessagesServices.Designer.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition.Services/Resources/ViewsMessagesServices.resx, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Controllers/TestController.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Resources/ViewsMessages.Designer.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Resources/ViewsMessages.resx, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/appsettings.Development.json
Error 404 after typing white char as an aswer
Please check issue to reproduce error. 
My changes were only in TestController - Index(int testNumber, string answer = "") method
closes #251 
I tested manually. Added question, and sends empty answer.
expected behavoiur:
=> Add modelState error when sending whitespace

src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Shared/_Layout.cshtml, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/wwwroot/css/site.css
=> Merge with develop

src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Shared/_LoginPartial.cshtml
Temporary disable login and register buttons in menu 
closes #387
Manually.
=> disabled login and register button

src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Shared/_LoginPartial.cshtml
=> disabled login and register button (#390)

src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Account/ExternalLogin.cshtml
=> Fix external account linkage

src/DevAdventCalendarCompetition/DevAdventCalendarCompetition.Services/Interfaces/IManageService.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition.Services/ManageService.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Controllers/ManageController.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Resources/ExceptionsMessages.Designer.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Resources/ExceptionsMessages.resx, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Manage/Index.cshtml
The user profile view has now unlocked option to change the user name. 
#353 
Sign in, go to the user profile view, change the user name.
=> Added possibility for user to change his user name.

src/DevAdventCalendarCompetition/DevAdventCalendarCompetition.Tests/UnitTests/Controllers/TestControllerTests.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Controllers/TestController.cs
Error 404 after clicking on day for which test was finished earlier
I did changes in TestController
closes #253
Manually
Test scenarios:
1) a test that does not exist (9999) /Test/Index?testNumber=9999
2) existing test already closed that you didn't answer  /Test/Index?testNumber=14
3) existing test not started  /Test/Index?testNumber=17
Please, have in mind that with that scenario user will not ble able to "click" not started test:
=> check if test exists if not - 404

src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/appsettings.Production.json
Fix for production appsettings.json file.
Fixed production appsettings.json file.
Deploy on dev env, check if application starts.
Oversight from previous PR
appsettings.json was already modified manually in container, after restart application boots up correctly.
=> Fixed properties tree

src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Account/Register.cshtml
I've excluded the "Calendar" scheme from the schemes to login.
Go to "Account/Register" page.
=> Exclude Calendar schema from login

src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Resources/ViewsMessages.Designer.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Resources/ViewsMessages.resx
=> Fix prizes view

src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Resources/ViewsMessages.Designer.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Resources/ViewsMessages.resx, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Home/Index.cshtml, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/wwwroot/theme-2019/style.css
Added widget on the home page.
closes #457 
Run app, open home page.
=> Zrzutka.pl charity widget.

src/DevAdventCalendarCompetition/DevAdventCalendarCompetition.Services/GoogleCalendarService.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/appsettings.json
I've changed test opening hour in appsettings and event end hour in google calendar to test's end hour.
Close #448 
Manually
=> Set opening time in appsettings

src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Results/_ResultsPage.cshtml
First columns have strange header 'System.Security.Claims.ClaimsPrincipal' -> need to be changed to 'Nazwa użytkownika'. **Done**
Other task from #466 were fixed previously. 
Views -> Results -> _ResultsPage
closes  #466
=> fix user name in Results View

src/DevAdventCalendarCompetition/DevAdventCalendarCompetition.Repository/Interfaces/IStatisticsRepository.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition.Repository/StatisticsRepository.cs
=> Fix for no user answers in TestAnswers

src/DevAdventCalendarCompetition/DevAdventCalendarCompetition.Tests/UnitTests/Controllers/TestControllerTests.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Controllers/TestController.cs
I've added missing check to Test controller.
Test: Started/Ended and answered
Test: Ended and not answered
Test: Started and not answered
Test: Not started
=> Visibility of other tests

src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Home/Partners.cshtml
fix sponsor page
Partners page
=> fix in sponsor page

src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Resources/ViewsMessages.Designer.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Resources/ViewsMessages.resx
Changed coupon count.
Open app.
Open prizes page and look at the Helion coupons count.
=> Changed coupon count

src/DevAdventCalendarCompetition/DevAdventCalendarCompetition.Repository/Models/UserTestCorrectAnswer.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition.Repository/UserTestAnswersRepository.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition.TestResultService.Tests/TestResultServiceTest.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition.TestResultService.Tests/TestResultServiceTestFixture.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition.TestResultService.Tests/UserTestAnswersRepositoryFixture.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition.TestResultService.Tests/UserTestAnswersRepositoryTest.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition.Tests/IntegrationTests/ResultsServiceTests.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition.Tests/TestHelper.cs
…imeSumPerUserForDateRange in UserTestAnswersRepository to consider only first correct answer
=> Modify test answer stats

src/DevAdventCalendarCompetition/DevAdventCalendarCompetition.Services/ResultsService.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition.Tests/IntegrationTests/ResultsServiceTests.cs
Changed year for result display to be based on current competition date.
closes #504 
Run app, check results are showing correctly for current year.
=> Changed year for result display to be based on current competition date.

src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Home/Partners.cshtml
=> Aktualizacja partnerów

src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Home/Partners.cshtml
Updated media partners - WarsawJS & JuniorPyta.pl
=> Updated two media partners.

src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Home/Index.cshtml
=> Updated charity action Zrzutka.pl

src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Home/Index.cshtml
=> Changed the widget width

src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Home/Partners.cshtml
=> Changed partners placement

src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Controllers/HomeController.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Home/About.cshtml, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Home/Faq.cshtml, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Shared/_Layout.cshtml, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/wwwroot/theme-2019/style.css
=> Added FAQ page

src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Resources/ViewsMessages.Designer.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Resources/ViewsMessages.resx
=> Fixed prizes description

src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Home/Partners.cshtml
=> Partner remove

src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Resources/ViewsMessages.Designer.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Resources/ViewsMessages.resx
- [z] Bug fix (non-breaking change which fixes an issue)
=> Fixed wrong result days descriptions

src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Resources/ViewsMessages.Designer.cs, src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Resources/ViewsMessages.resx
=> Fixed typos

src/DevAdventCalendarCompetition/DevAdventCalendarCompetition.TestResultService/TestResultService.cs
To be able to pass 1st test for everyone in competition
=> Added temporary starting result calculation from 2nd of December

src/DevAdventCalendarCompetition/DevAdventCalendarCompetition.TestResultService/TestResultService.cs
=> Restore results calculations start to 1st of December.

src/DevAdventCalendarCompetition/DevAdventCalendarCompetition.Services/AdventService.cs
Added day to the competition end date limit.
=> Fixed checking advent end date
